export interface ICarType {
  carId: number;
  imagePath: string;
  brand: string;
  model: string;
  year: number;
  price: string;
  isFavorite: boolean;
  fuelType: string;
  engine: string;
  transmission: string;
  color: string;
  mileage: number;
  interiorColor: string;
  kilometersPerLiter: number;
}

export const CARS_MOCK_DATA: ICarType[] = [
  {
    carId: 1,
    imagePath: '/assets/audi.jpeg',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2022,
    price: `120.000`,
    isFavorite: true,
    fuelType: 'Gasoline',
    engine: '1.8L Inline-4',
    transmission: 'Automatic',
    color: 'Silver',
    mileage: 25000,
    interiorColor: 'Black',
    kilometersPerLiter: 15,
  },
  {
    carId: 2,
    imagePath: '/assets/civic.jpg',
    brand: 'Honda',
    model: 'Civic',
    year: 2023,
    price: `125.000`,
    isFavorite: false,
    fuelType: 'Gasoline',
    engine: '2.0L Inline-4',
    transmission: 'CVT',
    color: 'White',
    mileage: 15000,
    interiorColor: 'Gray',
    kilometersPerLiter: 14,
  },
  {
    carId: 3,
    imagePath: '/assets/mustang.jpg',
    brand: 'Ford',
    model: 'Mustang',
    year: 2021,
    price: `150.000`,
    isFavorite: false,
    fuelType: 'Gasoline',
    engine: '5.0L V8',
    transmission: 'Manual',
    color: 'Red',
    mileage: 18000,
    interiorColor: 'Black',
    kilometersPerLiter: 10,
  },
  {
    carId: 4,
    imagePath: '/assets/camaro.jpg',
    brand: 'Chevrolet',
    model: 'Camaro',
    year: 2022,
    price: `145.000`,
    isFavorite: true,
    fuelType: 'Gasoline',
    engine: '6.2L V8',
    transmission: 'Automatic',
    color: 'Black',
    mileage: 22000,
    interiorColor: 'Red',
    kilometersPerLiter: 9,
  },
  {
    carId: 5,
    imagePath: '/assets/nissangtr.jpeg',
    brand: 'Nissan',
    model: 'GT-R',
    year: 2023,
    price: `180.000`,
    isFavorite: false,
    fuelType: 'Gasoline',
    engine: '3.8L V6 Twin-Turbo',
    transmission: 'Automatic',
    color: 'Blue',
    mileage: 8000,
    interiorColor: 'Black',
    kilometersPerLiter: 8,
  },
  {
    carId: 6,
    imagePath: '/assets/bmwm5.jpeg',
    brand: 'BMW',
    model: 'M5',
    year: 2022,
    price: `160.000`,
    isFavorite: false,
    fuelType: 'Gasoline',
    engine: '4.4L V8 Twin-Turbo',
    transmission: 'Automatic',
    color: 'Gray',
    mileage: 12000,
    interiorColor: 'Beige',
    kilometersPerLiter: 11,
  },
  {
    carId: 7,
    imagePath: '/assets/mercedes.jpeg',
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2023,
    price: `155.000`,
    isFavorite: false,
    fuelType: 'Gasoline',
    engine: '2.0L Inline-4',
    transmission: 'Automatic',
    color: 'Silver',
    mileage: 9000,
    interiorColor: 'Black',
    kilometersPerLiter: 13,
  },
  {
    carId: 8,
    imagePath: '/assets/audi.jpeg',
    brand: 'Audi',
    model: 'A4',
    year: 2022,
    price: `140.000`,
    isFavorite: false,
    fuelType: 'Gasoline',
    engine: '2.0L Inline-4',
    transmission: 'Automatic',
    color: 'Black',
    mileage: 14000,
    interiorColor: 'Gray',
    kilometersPerLiter: 14,
  },
  {
    carId: 9,
    imagePath: '/assets/fusion.jpeg',
    brand: 'Ford',
    model: 'Fusion',
    year: 2022,
    price: `127.000`,
    isFavorite: false,
    fuelType: 'Hybrid',
    engine: '2.0L Inline-4 + Electric Motor',
    transmission: 'CVT',
    color: 'White',
    mileage: 18000,
    interiorColor: 'Beige',
    kilometersPerLiter: 20,
  },
  {
    carId: 10,
    imagePath: '/assets/x6.jpg',
    brand: 'BMW',
    model: 'X6',
    year: 2021,
    price: `600.000`,
    isFavorite: false,
    fuelType: 'Gasoline',
    engine: '4.4L V8 Twin-Turbo',
    transmission: 'Automatic',
    color: 'Black',
    mileage: 9000,
    interiorColor: 'Black',
    kilometersPerLiter: 8,
  },
];
